service: serverless-api
frameworkVersion: '2.68.0'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: controllers/hello.default
    events:
      - httpApi:
          method: get
          path: /hello
          cors: true
  imagePresignedURL:
    handler: controllers/images.getPresignedURL
    cors: true
    events:
      - httpApi:
          method: get
          path: /image/presigned-url
          cors: true
  