service: serverless-webpack-typescript-example
frameworkVersion: '2.61.0'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: controllers/hello.default
    events:
      - httpApi:
          method: get
          path: hello
          integration: lambda