name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Install packages
      run: |
        npm ci
        npm i -g serverless@2.69.1
    - name: Create .env file
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_DEPLOYMENT_BUCKET_NAME: ${{ secrets.AWS_DEPLOYMENT_BUCKET_NAME }}
        REGION: ${{ secrets.REGION }}
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        touch .env
        echo AWS_BUCKET_NAME=${AWS_BUCKET_NAME} >> .env
        echo AWS_DEPLOYMENT_BUCKET_NAME=${AWS_DEPLOYMENT_BUCKET_NAME} >> .env
        echo REGION=${REGION} >> .env
        echo FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS} >> .env
        ls
    - name: Deploy
      run: sls deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}