on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test before deploy to dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: |
        npm ci
        npm i -g serverless@2.69.1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - run: npm run test
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_DEPLOYMENT_BUCKET_NAME: ${{ secrets.AWS_DEPLOYMENT_BUCKET_NAME }}
        REGION: ${{ secrets.REGION }}
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}